import Vue from 'vue';
import { Button } from 'vant';
Vue.use(Button);
import { Cell, CellGroup } from 'vant';
Vue.use(Cell);
Vue.use(CellGroup);
import { Icon } from 'vant';
Vue.use(Icon);
import { Image as VanImage } from 'vant';
Vue.use(VanImage);
import { Popup } from 'vant';
Vue.use(Popup);
import { Checkbox, CheckboxGroup } from 'vant';
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
import { DatetimePicker } from 'vant';
Vue.use(DatetimePicker);
import { Field } from 'vant';
Vue.use(Field);
import { Form } from 'vant';
Vue.use(Form);
import { NumberKeyboard } from 'vant';
Vue.use(NumberKeyboard);
import { Picker } from 'vant';
Vue.use(Picker);
import { RadioGroup, Radio } from 'vant';
Vue.use(Radio);
Vue.use(RadioGroup);
import { Search } from 'vant';
Vue.use(Search);
import { Switch } from 'vant';
Vue.use(Switch);
import { Uploader } from 'vant';
Vue.use(Uploader);
import { Dialog } from 'vant';
Vue.use(Dialog);
import { Loading } from 'vant';
Vue.use(Loading);
import { ImagePreview } from 'vant';
Vue.use(ImagePreview);
import { Lazyload } from 'vant';
Vue.use(Lazyload, {
  lazyComponent: true,
});
import { NavBar } from 'vant';
Vue.use(NavBar);
import { Tab, Tabs } from 'vant';
Vue.use(Tab);
Vue.use(Tabs);
import { Tabbar, TabbarItem } from 'vant';
Vue.use(Tabbar);
Vue.use(TabbarItem);
import { List } from 'vant';
Vue.use(List);
import { Divider } from 'vant';
Vue.use(Divider);
import { Calendar } from 'vant';
Vue.use(Calendar);
import { Pagination } from 'vant';
Vue.use(Pagination);
